name: little_bird
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^3.1.14
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  gap: ^3.0.1
  mobx: ^2.3.3+2
  flutter_mobx: ^2.0.0
  linkfy_text: ^1.1.6
  shared_preferences: ^2.3.2
  selectable_autolink_text: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  mobx_codegen: ^2.0.0
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/developer/
    - assets/branding/
    - assets/branding/alternatives/
    - assets/branding/original/

scripts:
  mobx_watch: flutter pub run build_runner watch --delete-conflicting-outputs
  mobx_build: flutter pub run build_runner build --delete-conflicting-outputs